---
# The Consul Master key/token to be used to bootstrap ACLs for the cluster.
#
# Below is an example token; keep yours secret. Keep it safe.
consul_master_key: "58b39ecd-614c-5094-a4ae-c4db5c08e496"

# The Vault token, with access to the kv-v1 store, to be used to store
# Consul ACLs.
#
# Below is an example token; keep yours secret. Keep it safe.
vault_master_token: "s.79CriBBzcm4cpFaQexmG0lHT"

# A `target_`-namespaced variable (to avoid conflicts), with the value of the
# primary vault datacenter, for access via Consul-configured DNS.
target_vault_primary_datacenter: dc1
