---
# The Consul Master key/token to be used to bootstrap ACLs for the cluster.
consul_master_key: "bc2b0299-e39d-43a2-aea8-1a5cc9684ec6"

# The Vault token, with access to the kv-v1 store, to be used to store
# Consul ACLs.
vault_master_token: "s.xxxxxxxxxxxxxxxxxxxxx"

# A `target_`-namespaced variable (to avoid conflicts), with the value of the
# primary vault datacenter, for access via Consul-configured DNS.
target_vault_primary_datacenter: global
